## This Action creates a new 'patch-*' branch with the next semantic version number
##  - Manually run by developer wiht input of branch to patch off of
##  - must be created off of `main` or `release-*` branch
##  - creates a PR against the branch it was cut off of

name: "Patch-Cut"

# Workflow runs when manually triggered using the UI or API
on: workflow_dispatch
 
jobs:
  cut-patch:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
      with:
        ## This is a Personal Access Token from Admin User that allows us to bypass branch protections on develop
        token: ${{ secrets.PAT }}
        fetch-depth: 0

    - name: "Error if not in main or release branch"
      id: branch
      run: |
        ./scripts/release/patch-cut-check.sh ${GITHUB_REF##*/};
        echo "##[set-output name=release;]${GITHUB_REF##*/}";

    - name: "Get Version Info"
      id: version
      run: |
        git fetch --all --tags;
        cd scripts/release;
        unzip git-mkver-linux.zip;
        cd ../..;
        echo "##[set-output name=major;]$(./scripts/release/git-mkver-linux next --format '{Major}')";
        echo "##[set-output name=minor;]$(./scripts/release/git-mkver-linux next --format '{Minor}')";
        echo "##[set-output name=patch;]$(./scripts/release/git-mkver-linux next --format '{Patch}')";


    - name: "Generate Next Version Number"
      id: next_version
      run: |
        echo "##[set-output name=patch;]$(($PATCH_VERSION+1))"
      env:
        PATCH_VERSION: ${{ steps.version.outputs.patch }}

    - name: "Create Patch Branch"
      run: |
        git config --global user.name 'Release Cut';
        git config --global user.email 'release@cut.com';
        git checkout -b $PATCH_BRANCH;
        ./scripts/release/update-versions.sh $PATCH_VERSION;
        git commit -a -m "update version for $PATCH_BRANCH";
        git push --set-upstream origin $PATCH_BRANCH;
      env:
        PATCH_BRANCH: patch-${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.next_version.outputs.patch }}
        PATCH_VERSION: ${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.next_version.outputs.patch }}

       # Note: see https://github.com/repo-sync/pull-request#advanced-options for all options
    - name: Create Patch Pull Request
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.PAT }}
        source_branch: patch-${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.next_version.outputs.patch }}
        destination_branch: ${{ steps.branch.outputs.release }}
        pr_title: patch-${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.next_version.outputs.patch }}
        pr_body: ${{ steps.version.outputs.changelog }}
        pr_label: "- release -"